version: "3.8"
services:
  market-bot-config-api-sb:
    container_name: market-bot-config-api-sb-prod
    image: bananaztech/market-bot-config-api-sb:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: URL
      SPRING_DATASOURCE_USERNAME: USERNAME
      SPRING_DATASOURCE_PASSWORD: PASSWORD
    ports:
      - "8091:8080"
      - "8007:9000"

networks:
  default:
    external:
      name: frontend