apiVersion: v1
kind: Namespace
metadata:
  name: market-bot-config-api
---
apiVersion: v1
kind: Service
metadata:
  namespace: market-bot-config-api
  name: market-bot-config-api-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    service: market-bot-config-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: market-bot-config-api
  name: market-bot-config-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: market-bot-config-api
  template:
    metadata:
      labels:
        service: market-bot-config-api
    spec:
      restartPolicy: Always
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: "abcd1234!"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://10.0.0.0:3306/MarketBotConfigs?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: marketbots-svc-acct
          image: bananaztech/market-bot-config-api-sb:latest
          imagePullPolicy: Always
          name: market-bot-config-api
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 500Mi
              cpu: 300m
            requests:
              memory: 250Mi
              cpu: 250m
---